apiVersion: v1
kind: Secret
metadata:
  name: wp-secrets
  namespace: wordpress
type: Opaque
stringData:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wpuser
  MYSQL_PASSWORD: wppass123
  MYSQL_ROOT_PASSWORD: rootpass123
