apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: blog
    app.kubernetes.io/component: frontend   # (ou database pour mariadb)
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app: wordpress
  ports:
    - name: http
      port: 80
      targetPort: 80
      #nodePort: 30081   # NodePort dédié pour WP
