apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081   # NodePort dédié pour WP
